services:
  - type: web
    name: missevan-id-count
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: ENABLE_MISSEVAN
        value: "false"
